### ISSUE TITLE
Add Spring Boot 2.0 compatibility

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-stream-app-starters/app-starters-release#134]
As a developer, I'd like to add Spring Boot 2.0 compatibility for the OOTB apps.

**Acceptance:**
- Ensure Spring Boot, Spring Cloud, Spring Cloud Stream and the ecosystem is on 2.0 line
- Ensure README/docs are up-to-date
- Ensure tests run successfully

**Targeted Apps:**

- [x] time-source @tzolov
- [x] log-sink @tzolov
- [x] http-source
- [x] file-source @artembilan
- [x] file-sink @artembilan
- [x] filter-processor
- [x] splitter-processor soby
- [x] transform-processor 
- [x] aggregator-processor @artembilan 
- [x] ftp-source (see also https://github.com/spring-cloud-stream-app-starters/ftp/issues/7)
- [x] ftp-sink (see also https://github.com/spring-cloud-stream-app-starters/ftp/issues/6)
- [x] sftp-source 
- [x] sftp-sink 
- [x] bridge-processor
- [x] jdbc-source 
- [x] jdbc-sink
- [x] gemfire-source @tzolov
- [x] groovy-filter-processor
- [x] groovy-transform-processor soby
- [x] httpclient-processor 
- [x] header-enricher-processor
- [x] trigger-source @tzolov
- [x] triggertask-source
- [x] task-launcher-cloudfoundry-sink @sobychacko 
- [x] tasklaunchrequest-transform-processor
~- [ ] cassandra-sink~
- [x] twitterstream-source @tzolov
- [x] aggregate-counter-sink (see also https://github.com/spring-cloud-stream-app-starters/aggregate-counter/issues/3) @sobychacko 
- [x] counter-sink @sobychacko 
- [x] field-value-counter-sink @sobychacko 
- [x] hdfs-sink @jvalkeal / @trisberg _(depends on SHDP)_
~- [ ] hdfs-dataset-sink @jvalkeal / @trisberg _(depends on SHDP)_~
- [x] tcp-source (see also https://github.com/spring-cloud-stream-app-starters/tcp/issues/5) @tzolov
- [x] tcp-sink (see also https://github.com/spring-cloud-stream-app-starters/tcp/issues/8) @tzolov
- [x] tcp-client-source (see also https://github.com/spring-cloud-stream-app-starters/tcp/issues/6) @tzolov
- [x] tcp-client-processor (see also https://github.com/spring-cloud-stream-app-starters/tcp/issues) @tzolov
- [x] pgcopy-sink
- [x] router-sink soby
- [x] scriptable-transform-processor @artembilan
- [x] task-launcher-local-sink
- [x] task-launcher-yarn-sink
- [x] throughput-sink
- [x] websocket-sink
~- [ ] gpfdist-sink @tzolov~
- [x] load-generator-source (see also https://github.com/spring-cloud-stream-app-starters/load-generator/issues/3)
- [x] loggregator-source
- [x] rabbit-source
- [x] rabbit-sink
- [x] syslog-source 
- [x] jms-source 
- [x] redis-pubsub-sink
- [x] mail-source
- [x] gemfire-sink @tzolov
- [x] gemfire-cq-source @tzolov
- [x] mongodb-source
- [x] mongodb-sink
- [x] pmml-processor @tzolov
- [x] tensorflow-processor
- [x] twitter-sentiment-processor
- [x] s3-source (see also https://github.com/spring-cloud-stream-app-starters/aws-s3/issues/1)
- [x] s3-sink 
- [x] python-http-processor 
- [x] python-jython-processor 
- [x] mqtt-source
- [x] mqtt-sink

**Comment by artembilan** [comment]
In addition to this story I would like to suggest also to consider to fix Apps generator plugin to rename the Kafka based apps. Because right now it is for example `jdbc-sink-kafka-10`, where our Kafka version support is `1.0.0`.

**Comment by garyrussell** [comment]
Agreed; in 2.0 there is only one kafka binder (unless kafka-clients 1.1.0 is released and has API changes 😦  )

**Comment by artembilan** [comment]
We have race condition with this checkboxes hell again. 

I definitely remember how I marked yesterday `s3` and `jdbc` as fixed yesterday.
And they are not today again...

On the other hand I don't think that `tcp` and `tensorflow` projects are fixed though, @tzolov ...
Right, they might be in PRs, but not merged yes AFAIK.

Thanks, but let's consider some other "leader election" mechanism!

**Comment by tzolov** [comment]
@artembilan, my understanding is that the checkboxes are just to mark someones interest in resolving a certain app(s). To coordinate and to prevent overlaps. 
So by checking a box i want to show that i intend to fix the checked apps not that it is already resolved.  I guess we can add a second checkbox to the apps for indicating their resolution status
