### ISSUE TITLE
Refactor and port apps to functions repo

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-stream-app-starters/app-starters-release#222]
Following artifacts/apps need to be released as part of the Fahrenheit GA release train. 

List sorted by maven-central's download frequency aka a rough take on priority:

- [x] http-source  - @artembilan @sobychacko
- [ ] rabbit-source  - @sobychacko 
- [x] rabbit-sink  - @sobychacko 
- [ ] gemfire-source  - 
- [ ] gemfire-sink  - **ready** @tzolov 
- [ ] gemfire-cq-source - 
- [x] log-sink - @sobychacko
- [x] jdbc-source  - @sobychacko
- [ ] jdbc-sink  - **functio-ready** @sobychacko 
- [ ] ftp-source - -  @dturanski
- [ ] ftp-sink - 
- [x] mongodb-source - @dturanski @sobychacko Fahrenheit-M2
- [x] mongodb-sink - @dturanski @sobychacko Fahrenheit-M2
- [ ] sftp-source -  @dturanski _(in-progress)_ 
- [ ] sftp-sink -   
- [x] router-sink - (app only)
- [x] counter-sink - @tzolov Fahrenheit-M2
- [x] splitter-processor - @artembilan @sobychacko
- [x] time-source - @sobychacko 
- [ ] httpclient-processor - **ready** @artembilan (it will be based on WebFlux)
- [x] filter-processor - **function-done** @sobychacko Fahrenheit-M2
- [x] transform-processor  - **function-done** @sobychacko Fahrenheit-M2
- [x] bridge-processor - (app only)
- [ ] jms-source  - @tzolov @artembilan (we will have to make reactive adjustments in SI)
- [x] tcp-source   - (app only)
- [x] tcp-sink   - (app only)
- [x] tcp-client-source    - (app only)
- [x] tcp-client-processor    - (app only)
- [x] groovy-filter-processor - (app only)
- [x] groovy-transform-processor - (app only)
- [x] header-enricher-processor - function ready
- [x] s3-source  - (app only)
- [x] s3-sink  - (app only)
- [x] file-source  - @artembilan 
- [x] file-sink  - @artembilan 
- [x] mqtt-source  - (app only)
- [x] mqtt-sink  - (app only)
- [ ] aggregator-processor -
- [x] cassandra-sink - @artembilan @sobychacko Fahrenheit-M2
- [x] load-generator-source - (app only)
- [x] loggregator-source - (app only)
- [x] mail-source - (app only)
- [x] pgcopy-sink  - (app only)
- [x] pmml-processor - (app only)
- [x] redis-pubsub-sink - function ready
- [x] scriptable-transform-processor - (app only)
- [x] syslog-source   - (app only)
- [x] throughput-sink - (app only)
- [x] trigger-source   - (app only)
- [ ] triggertask-source  - ?? (deperecated?)
- [ ] twitterstream-source  - check with Christian.
- [x] websocket-sink - (app only)
- [ ] image-recognition-porocessor - check with Christian.
- [ ] pose-estimation-porocessor - check with Christian.
- [ ] tasklaunchrequest-transform-porocessor - Dave
- [ ] tasklauncher-dataflow - @dturanski _(in pr)_ Dave
- [ ] tensorflow-porocessor - check with Christian.
- [x] grpc-porocessor - (app only)
- [x] python-http-porocessor - (app only)
- [x] python-jython-porocessor - (app only)
- [ ] twitter-sentiment-porocessor - check with Christian.
- [ ] object-detection-porocessor - check with Christian.
- [ ] hdfs-sink - Check with Janne

**App Starters Infra Repo:**
spring-cloud/stream-applications

**Notes:**
1) Since we don't have any CI in place, we need to build them locally first (install function artifacts first)
2) We may have to rely on the unit-tests in the functions repo; however, a full-blown IT or AT type of tests should surface at each app-starter level. That means, we will need new CI plans, for different binders, too.

_Here are the steps:_
1. Clone github.com/pivotal/java-functions
2. > ./mvnw clean install
3. Clone https://github.com/spring-cloud-stream-app-starters/stream-apps
4. > ./mvnw clean package (or do it from the corresponding app modules)

**Comment by dturanski** [comment]
@sabbyanandan @sobychacko - I assume for the `sftp` source we will remove all task launch request related code, including for the new app starter, and show how to use function composition to do the file ingest UC. - We will need to include https://github.com/spring-cloud-stream-app-starters/core/tree/master/common/app-starters-task-launch-request-common in the new function repo.
